### ISSUE TITLE
Street matched to municipality but not sub municipality

### ISSUE THREAD

**Issue by wouterds** [aptum/aptum.github.io#2]
Hi,

First: good job on this tool. Looks very promising.

I was making my own to parse it but ran into a problem, I can't match a street to the correct sub municipality (deelgemeente). Only the correct municipality (gemeente).

For example: Rietvoornstraat 2, 9800 Astene.

If you trace it completely it is linked to GEM 273 (Deinze) which is correct. But then in the POSTKANNM table it says Astene/Bachte-Maria-Leerne/Grammene/Deinze etc..

There's no way to link it the correct one from this list it seems. I see in your data dump that it also says [9800, Deinze](https://github.com/aptum/aptum.github.io/blob/master/data/9800/rietvoornstraat.json). Which is correct, but it can be more specific. Because right now we don't know it's 9800 Astene, Deinze. It could be as well 9800 Grammene, Deinze.

There's no way you can think of to link it to the correct sub municipality?

![Screenshot](https://pbs.twimg.com/media/CUBWOacWwAARKTr.jpg:large)

Cheers,
Wouter

**Comment by sanderd17** [comment]
bPost and most other official instances only use the municipality in the address now (see the bPost guidelines on writing addresses).

But I know that many locals still prefer to refer to their part-municipality, partially for nostalgic reasons, partially because that name is more precise and thus makes it easier to find addresses.

In any case, official data referring to part-municipalities is very sparse, so I can't help you with that. The best data available is probably already in OSM. We spend many months digitizing ancient paper maps to reproduce the boundaries.
